# report only problems not all passed checks
quiet: true
skip-check:
  # Ensure that HEALTHCHECK instructions have been added to container images
  - CKV_DOCKER_2
  # Ensure that a user for the container has been created
  - CKV_DOCKER_3
  # Ensure the base image uses a non latest version tag
  - CKV_DOCKER_7
  # Allow input parameters to workflows
  - CKV_GHA_7
